BethanysPieShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BethanysPieShop/Controllers/PieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BethanysPieShop.Models;
using BethanysPieShop.Services;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository ?? throw new ArgumentNullException(nameof(pieRepository));
            _categoryRepository = categoryRepository ?? throw new ArgumentNullException(nameof(categoryRepository));
        }

        // public ViewResult List()
        // {
        //     var piesListViewModel = new PiesListViewModel()
        //     {
        //         Pies = _pieRepository.AllPies,
        //         CurrentCategory = "Cheese cakes"
        //     };
        //     return View(piesListViewModel);
        // }

        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.AllPies
                    .OrderBy(pie => pie.PieId);
                currentCategory = "All pies";
            }
            else
            {
                pies = _pieRepository.AllPies
                    .Where(pie => pie.Category.CategoryName == category)
                    .OrderBy(pie => pie.PieId);
                currentCategory = _categoryRepository.AllCategories
                    .FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }

        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null) return NotFound();

            return View(pie);
        }
    }
}

BethanysPieShop/Controllers/ShoppingCartController.cs
using System;
using BethanysPieShop.Services;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IPieRepository pieRepository, ShoppingCart shoppingCart)
        {
            _pieRepository = pieRepository ?? throw new ArgumentNullException(nameof(pieRepository));
            _shoppingCart = shoppingCart ?? throw new ArgumentNullException(nameof(shoppingCart));
        }

        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int pieId)
        {
            var selectedPie = _pieRepository.GetPieById(pieId);
            if (selectedPie != null) 
                _shoppingCart.AddToCart(selectedPie, 1);

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int pieId)
        {
            var selectedPie = _pieRepository.GetPieById(pieId);
            if (selectedPie != null) 
                _shoppingCart.RemoveFromCart(selectedPie);

            return RedirectToAction("Index");
        }
    }
}

BethanysPieShop/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

BethanysPieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/content/site.css">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                @await Component.InvokeAsync("CategoryMenu")
                <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>

                @await Component.InvokeAsync("ShoppingCartSummary")
                <partial name="_LoginPartial"></partial>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p class="lead">
                <img src="~/images/bethanylogo.png" alt="Bethany's Pie Shop" class="img-responsive">
            </p>
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>
@RenderSection("Scripts", required: false)
</body>
</html>

BethanysPieShop/Views/Shared/_PieCard.cshtml
@model Pie

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="@Model.Name">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("C")</h3>
            <h3>
                <a asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>